# Generated by Django 4.1.2 on 2022-11-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answer_modify_date_question_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
    ]
